# game_data.py
# A list of entities with follower_count (in millions), short description, and country.
# You can tweak counts anytime to rebalance difficulty.

data = [
    {
        "name": "Cristiano Ronaldo",
        "follower_count": 635,
        "description": "Footballer",
        "country": "Portugal",
    },
    {
        "name": "Taylor Swift",
        "follower_count": 285,
        "description": "Singer-songwriter",
        "country": "USA",
    },
    {
        "name": "Lionel Messi",
        "follower_count": 505,
        "description": "Footballer",
        "country": "Argentina",
    },
    {
        "name": "Selena Gomez",
        "follower_count": 430,
        "description": "Singer & actress",
        "country": "USA",
    },
    {
        "name": "Kylie Jenner",
        "follower_count": 400,
        "description": "Entrepreneur & media personality",
        "country": "USA",
    },
    {
        "name": "The Rock",
        "follower_count": 395,
        "description": "Actor & former wrestler",
        "country": "USA",
    },
    {
        "name": "Ariana Grande",
        "follower_count": 380,
        "description": "Singer & actress",
        "country": "USA",
    },
    {
        "name": "Kim Kardashian",
        "follower_count": 360,
        "description": "Entrepreneur & media personality",
        "country": "USA",
    },
    {
        "name": "Beyoncé",
        "follower_count": 320,
        "description": "Singer & performer",
        "country": "USA",
    },
    {
        "name": "Virat Kohli",
        "follower_count": 275,
        "description": "Cricketer",
        "country": "India",
    },
    {
        "name": "Neymar Jr",
        "follower_count": 220,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Billie Eilish",
        "follower_count": 120,
        "description": "Singer-songwriter",
        "country": "USA",
    },
    {
        "name": "Shakira",
        "follower_count": 95,
        "description": "Singer",
        "country": "Colombia",
    },
    {
        "name": "Rihanna",
        "follower_count": 150,
        "description": "Singer & entrepreneur",
        "country": "Barbados",
    },
    {
        "name": "Zendaya",
        "follower_count": 190,
        "description": "Actress",
        "country": "USA",
    },
    {
        "name": "LeBron James",
        "follower_count": 165,
        "description": "Basketball player",
        "country": "USA",
    },
    {
        "name": "NASA",
        "follower_count": 100,
        "description": "Space agency",
        "country": "USA",
    },
    {
        "name": "National Geographic",
        "follower_count": 285,
        "description": "Magazine & media",
        "country": "USA",
    },
    {
        "name": "FC Barcelona",
        "follower_count": 125,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "Real Madrid",
        "follower_count": 140,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "PSG",
        "follower_count": 75,
        "description": "Football club",
        "country": "France",
    },
    {
        "name": "Manchester United",
        "follower_count": 65,
        "description": "Football club",
        "country": "UK",
    },
    {
        "name": "Google",
        "follower_count": 45,
        "description": "Tech company",
        "country": "USA",
    },
    {
        "name": "YouTube",
        "follower_count": 40,
        "description": "Video platform",
        "country": "USA",
    },
    {
        "name": "Instagram",
        "follower_count": 675,
        "description": "Social platform",
        "country": "USA",
    },
    {
        "name": "MrBeast",
        "follower_count": 120,
        "description": "YouTuber & philanthropist",
        "country": "USA",
    },
    {
        "name": "PewDiePie",
        "follower_count": 30,
        "description": "YouTuber",
        "country": "Sweden",
    },
    {
        "name": "Bad Bunny",
        "follower_count": 50,
        "description": "Singer & rapper",
        "country": "Puerto Rico",
    },
    {
        "name": "BLACKPINK",
        "follower_count": 55,
        "description": "K-pop group",
        "country": "South Korea",
    },
    {
        "name": "BTS",
        "follower_count": 75,
        "description": "K-pop group",
        "country": "South Korea",
    },
    {
        "name": "Drake",
        "follower_count": 145,
        "description": "Rapper",
        "country": "Canada",
    },
    {
        "name": "Adele",
        "follower_count": 55,
        "description": "Singer-songwriter",
        "country": "UK",
    },
    {
        "name": "Ed Sheeran",
        "follower_count": 50,
        "description": "Singer-songwriter",
        "country": "UK",
    },
    {
        "name": "Justin Bieber",
        "follower_count": 290,
        "description": "Singer",
        "country": "Canada",
    },
    {
        "name": "KSI",
        "follower_count": 15,
        "description": "YouTuber & boxer",
        "country": "UK",
    },
    {
        "name": "Snoop Dogg",
        "follower_count": 85,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Will Smith",
        "follower_count": 75,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Emma Watson",
        "follower_count": 75,
        "description": "Actress & activist",
        "country": "UK",
    },
    {
        "name": "Chris Hemsworth",
        "follower_count": 60,
        "description": "Actor",
        "country": "Australia",
    },
    {
        "name": "Gigi Hadid",
        "follower_count": 80,
        "description": "Model",
        "country": "USA",
    },
    {
        "name": "Khaby Lame",
        "follower_count": 80,
        "description": "Creator",
        "country": "Italy/Senegal",
    },
    {
        "name": "Zendesk",
        "follower_count": 0.6,
        "description": "Customer service software",
        "country": "USA",
    },
    {
        "name": "OpenAI",
        "follower_count": 3.5,
        "description": "AI research lab",
        "country": "USA",
    },
    {
        "name": "FIFA World Cup",
        "follower_count": 50,
        "description": "Football tournament",
        "country": "Global",
    },
    {
        "name": "UEFA Champions League",
        "follower_count": 110,
        "description": "Football competition",
        "country": "Europe",
    },
    {
        "name": "Formula 1",
        "follower_count": 40,
        "description": "Motorsport series",
        "country": "Global",
    },
    {
        "name": "BMW",
        "follower_count": 40,
        "description": "Automotive brand",
        "country": "Germany",
    },
    {
        "name": "Nike",
        "follower_count": 310,
        "description": "Sportswear brand",
        "country": "USA",
    },
    {
        "name": "Adidas",
        "follower_count": 35,
        "description": "Sportswear brand",
        "country": "Germany",
    },
    {
        "name": "Netflix",
        "follower_count": 45,
        "description": "Streaming service",
        "country": "USA",
    },
    {
        "name": "Marvel Studios",
        "follower_count": 75,
        "description": "Film studio",
        "country": "USA",
    },
    {
        "name": "Starbucks",
        "follower_count": 20,
        "description": "Coffee company",
        "country": "USA",
    },
    {
        "name": "Dua Lipa",
        "follower_count": 90,
        "description": "Singer",
        "country": "UK",
    },
    {
        "name": "Karim Benzema",
        "follower_count": 75,
        "description": "Footballer",
        "country": "France",
    },
    {
        "name": "Erling Haaland",
        "follower_count": 50,
        "description": "Footballer",
        "country": "Norway",
    },
    {
        "name": "Kylian Mbappé",
        "follower_count": 120,
        "description": "Footballer",
        "country": "France",
    },
    {
        "name": "Olivia Rodrigo",
        "follower_count": 50,
        "description": "Singer & actress",
        "country": "USA",
    },
    {
        "name": "Shah Rukh Khan",
        "follower_count": 45,
        "description": "Actor",
        "country": "India",
    },
    {
        "name": "Al Nassr",
        "follower_count": 25,
        "description": "Football club",
        "country": "Saudi Arabia",
    },
]
